const REGISTER="REGISTER"
const LOGIN="LOGIN"
const LOGOUT="LOGOUT"
const SHOW_ALERT="SHOW_ALERT"
const CLEAR_ALERT="CLEAR_ALERT"
const CHANGE_PAGE="CHANGE_PAGE"
const CHANGE_SUBPAGE="CHANGE_SUBPAGE"
const GET_ALL_NEWS="GET_ALL_NEWS"
const  GET_ONE_NEWS=" GET_ONE_NEWS"
const GET_ALL_ANOUNCEMENT="GET_ALL_ANOUNCEMENT"
const GET_ONE_ANOUNCEMENT="GET_ONE_ANOUNCEMENT"

export {REGISTER,LOGIN,LOGOUT,SHOW_ALERT,CLEAR_ALERT,CHANGE_SUBPAGE
,CHANGE_PAGE,GET_ALL_NEWS, GET_ONE_NEWS,GET_ALL_ANOUNCEMENT,
GET_ONE_ANOUNCEMENT
}